### ISSUE TITLE
建议添加鉴权，或添加删除云端数据的方式

### ISSUE THREAD

**Issue by Doradx** [dpy1123/GithubRemark#7]
目前本插件缺乏API鉴权。
通过简单指令即可获取其它用户的备注信息，
例如：
```bash
curl --location 'https://promotion.devgo.top/github_remark/getRemark?token=dpy1123&username=yufan022'
```
通过以上命令即可简单获取到别人的备注信息，存在较大信息安全隐患。

**Comment by Ethkuil** [comment]
> 这个主要是我个人使用的，数据安全性确实没有太关注。你完全可以fork一下，把存储换到本地的local storage或者用你的私有gist存储。
> https://github.com/dpy1123/GithubRemark/issues/5#issuecomment-1200760152

**Comment by Doradx** [comment]
> > 这个主要是我个人使用的，数据安全性确实没有太关注。你完全可以fork一下，把存储换到本地的local storage或者用你的私有gist存储。
> > [#5 (comment)](https://github.com/dpy1123/GithubRemark/issues/5#issuecomment-1200760152)

我提交了pull，并已经合并到了这个项目：[tampermonkey/GitHubRemark.js](https://github.com/dpy1123/GithubRemark/blob/78d284b37d678ea464564282f7052775765b46fd/tampermonkey/GitHubRemark.js)
支持离线采用tampermonkey进行管理。
今天写博客的时候偶然发现我此前用此Chrome插件保存的数据还在云端，故手动进行了清空。
